// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Duel struct {
	ID        uuid.UUID
	Name      string
	Racer1ID  uuid.UUID
	Racer2ID  uuid.UUID
	RaceXp    int32
	Completed bool
	WinnerID  uuid.NullUUID
	StartTime time.Time
	EndTime   sql.NullTime
}

type Insult struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Insult string
}

type Progress struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Time    time.Time
	Level   int32
	Xp      int32
	TotalXp int32
	Lessons int32
}

type User struct {
	ID          uuid.UUID
	BootName    string
	DiscordName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Wizard      bool
	Nickname    string
	Target      bool
}
