// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: progress.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProgress = `-- name: CreateProgress :one
INSERT INTO progress (
    id,
    user_id,
    time,
    level,
    xp,
    total_xp,
    lessons
)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, time, level, xp, total_xp, lessons
`

type CreateProgressParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Time    time.Time
	Level   int32
	Xp      int32
	TotalXp int32
	Lessons int32
}

func (q *Queries) CreateProgress(ctx context.Context, arg CreateProgressParams) (Progress, error) {
	row := q.db.QueryRowContext(ctx, createProgress,
		arg.ID,
		arg.UserID,
		arg.Time,
		arg.Level,
		arg.Xp,
		arg.TotalXp,
		arg.Lessons,
	)
	var i Progress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Time,
		&i.Level,
		&i.Xp,
		&i.TotalXp,
		&i.Lessons,
	)
	return i, err
}
